name: CI

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Check result
        if: failure()
        run: echo "Commitlint failed!"